---
title: Blog
author: siberoloji
email: siberoloji@protonmail.com
description: 'Bu blog sitesinde Siber Konularda yazılar ve NASIL? dokümanları  yayınlamaktadır.


'
baseurl: ''
url: ''
twitter_username: portlinux
github_username: siberoloji
# Google services
google_analytics: UA-61059215-13
disqus.shortname: siberoloji-1.
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock

defaults:
  comments: true
