# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Siberoloji Blog 
email: siberoloji@protonmail.com
lang: tr_TR
description: > # this means to ignore newlines until "baseurl:"
  Bu sitede siber konularda yazılar yayınlanmaktadır.
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://siberoloji.github.io" # the base hostname & protocol for your site

#sidebar
default-image: cyber8.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda
copyright:
   name: siberoloji
   link: 'https://siberoloji.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 12
paginate_path: /page:num/

# Tracker
analytics: UA-61059215-13
google_cse_id: 000688360185781879140:kcvupy53t7m

# Comments
disqus-shortname: siberoloji-1

#social
twitter:
  username: siberegitim
twitter: https://twitter.com/@siberegitim
github: https://github.com/siberoloji
youtube: https://www.youtube.com/channel/UCalHdyzmz5W7L8BXQSUOXig
facebook: https://www.facebook.com/Siber-Konular-338514219818942/
moodle: http://egitim.siberoloji.com
links:
  - https://twitter.com/@siberegitim
  - https://github.com/siberoloji
  - https://plus.google.com/u/0/106526272070375055367
  - https://www.youtube.com/channel/UCalHdyzmz5W7L8BXQSUOXig
  - http://egitim.siberoloji.com

#facebook like box
fb-app-id: 348907038833482
fb-page-url: https://www.facebook.com/Siber-Konular-338514219818942/
fb-page-title: Siber Konular

# Sass style
sass:
  style: compressed

# Ruby Gems jekyll-seo-tag
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-sitemap, jekyll-google_cse]
